// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYbtkEie0inbm8sB3ZVxD7rf9JvA5zgBQ',
    appId: '1:221403492465:web:d2659b76c4f467c09d2bd0',
    messagingSenderId: '221403492465',
    projectId: 'veng-eang',
    authDomain: 'veng-eang.firebaseapp.com',
    storageBucket: 'veng-eang.appspot.com',
    measurementId: 'G-S4FLCQFH53',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBHjt_KE1QjnsVYGZgcElb0I59ZIYdgFzY',
    appId: '1:221403492465:android:4f02f948e5f574d09d2bd0',
    messagingSenderId: '221403492465',
    projectId: 'veng-eang',
    storageBucket: 'veng-eang.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7D55RFyKmDewj0nBnce4PFbN_5gipsec',
    appId: '1:221403492465:ios:8601292d671ea13e9d2bd0',
    messagingSenderId: '221403492465',
    projectId: 'veng-eang',
    storageBucket: 'veng-eang.appspot.com',
    iosBundleId: 'com.vengeang.portfolio',
  );
}
